133.5.11.11 - - [08/Sep/2017 15:09:01] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
133.5.11.11 - - [08/Sep/2017 15:09:06] "GET /jquery-3.1.1.min.js HTTP/1.1" 200 -
133.5.11.11 - - [08/Sep/2017 15:09:06] "GET /heatmap.min.js HTTP/1.1" 200 -
133.5.11.11 - - [08/Sep/2017 15:09:06] "GET /leaflet-heatmap.js HTTP/1.1" 200 -
133.5.11.11 - - [08/Sep/2017 15:09:06] "GET /cc-heatmap.js HTTP/1.1" 200 -
133.5.11.11 - - [08/Sep/2017 15:09:10] code 404, message File not found
133.5.11.11 - - [08/Sep/2017 15:09:10] "GET /favicon.ico HTTP/1.1" 404 -
133.5.11.11 - - [08/Sep/2017 15:23:32] "GET /cgi-bin/heatmap.py?datetime=201709081400 HTTP/1.1" 200 -
133.5.11.11 - - [08/Sep/2017 15:23:40] "GET /cgi-bin/heatmap.py?datetime=201709080900 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/crw/visualizer/cgi-bin/heatmap.py", line 117, in <module>
    print(html)
IOError: [Errno 104] Connection reset by peer
133.5.11.11 - - [08/Sep/2017 15:23:43] CGI script exit status 0x100
133.5.11.11 - - [08/Sep/2017 15:23:43] "GET /cgi-bin/heatmap.py?datetime=201709080900 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/crw/visualizer/cgi-bin/heatmap.py", line 117, in <module>
    print(html)
IOError: [Errno 104] Connection reset by peer
133.5.11.11 - - [08/Sep/2017 15:23:46] CGI script exit status 0x100
133.5.11.11 - - [08/Sep/2017 15:25:11] "GET /cgi-bin/heatmap.py?datetime=201709081200 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
133.5.11.11 - - [08/Sep/2017 15:25:11] "GET /cgi-bin/heatmap.py?datetime=201705091200 HTTP/1.1" 200 -
133.5.11.11 - - [08/Sep/2017 15:46:20] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
133.5.11.10 - - [08/Sep/2017 16:23:48] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
133.5.11.10 - - [08/Sep/2017 16:23:54] code 404, message File not found
133.5.11.10 - - [08/Sep/2017 16:23:54] "GET /favicon.ico HTTP/1.1" 404 -
133.5.11.10 - - [08/Sep/2017 16:24:26] "GET /cgi-bin/heatmap.py?datetime=201707031100 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/crw/visualizer/cgi-bin/heatmap.py", line 117, in <module>
    print(html)
IOError: [Errno 32] Broken pipe
133.5.11.10 - - [08/Sep/2017 16:24:30] CGI script exit status 0x100
133.5.11.10 - - [08/Sep/2017 16:24:30] "GET /cgi-bin/heatmap.py?datetime=201707031100 HTTP/1.1" 200 -
133.5.11.10 - - [08/Sep/2017 17:34:34] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
133.5.11.10 - - [08/Sep/2017 17:35:15] "GET /cgi-bin/heatmap.py?datetime=201704191100 HTTP/1.1" 200 -
133.5.90.71 - - [10/Sep/2017 09:58:04] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
133.5.90.71 - - [10/Sep/2017 09:58:12] code 404, message File not found
133.5.90.71 - - [10/Sep/2017 09:58:12] "GET /favicon.ico HTTP/1.1" 404 -
133.5.90.71 - - [10/Sep/2017 23:24:16] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
133.5.90.71 - - [10/Sep/2017 23:24:23] code 404, message File not found
133.5.90.71 - - [10/Sep/2017 23:24:23] "GET /favicon.ico HTTP/1.1" 404 -
133.5.90.71 - - [10/Sep/2017 23:25:35] "GET /cgi-bin/heatmap.py?datetime=201611191000 HTTP/1.1" 200 -
133.5.90.71 - - [10/Sep/2017 23:26:21] "GET /cgi-bin/heatmap.py?datetime=201706141000 HTTP/1.1" 200 -
133.5.90.71 - - [10/Sep/2017 23:27:24] "GET /cgi-bin/heatmap.py?datetime=201706141130 HTTP/1.1" 200 -
133.5.90.71 - - [10/Sep/2017 23:28:30] "GET /cgi-bin/heatmap.py?datetime=201706141200 HTTP/1.1" 200 -
133.5.90.71 - - [10/Sep/2017 23:29:41] "GET /cgi-bin/heatmap.py?datetime=201706141140 HTTP/1.1" 200 -
133.5.90.71 - - [11/Sep/2017 16:06:33] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
133.5.90.71 - - [11/Sep/2017 16:06:40] code 404, message File not found
133.5.90.71 - - [11/Sep/2017 16:06:40] "GET /favicon.ico HTTP/1.1" 404 -
133.5.90.71 - - [11/Sep/2017 16:07:24] "GET /cgi-bin/heatmap.py?datetime=201706141140 HTTP/1.1" 200 -
133.5.90.57 - - [12/Sep/2017 09:12:04] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
133.5.90.57 - - [12/Sep/2017 09:12:47] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
133.5.90.57 - - [12/Sep/2017 09:12:51] "GET /jquery-3.1.1.min.js HTTP/1.1" 200 -
133.5.90.57 - - [12/Sep/2017 09:12:51] "GET /heatmap.min.js HTTP/1.1" 200 -
133.5.90.57 - - [12/Sep/2017 09:12:51] "GET /leaflet-heatmap.js HTTP/1.1" 200 -
133.5.90.57 - - [12/Sep/2017 09:12:51] "GET /cc-heatmap.js HTTP/1.1" 200 -
133.5.90.57 - - [12/Sep/2017 09:12:53] code 404, message File not found
133.5.90.57 - - [12/Sep/2017 09:12:53] "GET /favicon.ico HTTP/1.1" 404 -
133.5.90.57 - - [12/Sep/2017 09:13:22] "GET /cgi-bin/heatmap.py?datetime=201704060910 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/crw/visualizer/cgi-bin/heatmap.py", line 117, in <module>
    print(html)
IOError: [Errno 32] Broken pipe
133.5.90.57 - - [12/Sep/2017 09:13:26] CGI script exit status 0x100
133.5.90.57 - - [12/Sep/2017 09:13:26] "GET /cgi-bin/heatmap.py?datetime=201704060910 HTTP/1.1" 200 -
133.5.90.57 - - [12/Sep/2017 09:45:35] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
133.5.90.71 - - [12/Sep/2017 10:16:11] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
133.5.90.71 - - [12/Sep/2017 10:16:16] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
133.5.90.71 - - [12/Sep/2017 10:16:21] code 404, message File not found
133.5.90.71 - - [12/Sep/2017 10:16:21] "GET /favicon.ico HTTP/1.1" 404 -
133.5.90.57 - - [12/Sep/2017 10:45:37] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/crw/visualizer/cgi-bin/heatmap.py", line 117, in <module>
    print(html)
IOError: [Errno 32] Broken pipe
133.5.90.57 - - [12/Sep/2017 10:45:40] CGI script exit status 0x100
133.5.90.57 - - [12/Sep/2017 10:46:57] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
133.5.90.57 - - [12/Sep/2017 10:51:13] "GET /jquery-3.1.1.min.js HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/home/crw/.pyenv/versions/2.7.12/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
133.5.90.57 - - [12/Sep/2017 11:06:44] "GET /leaflet-heatmap.js HTTP/1.1" 200 -
133.5.90.71 - - [12/Sep/2017 11:06:44] "GET /cgi-bin/heatmap.py HTTP/1.1" 200 -
